const beige: string = "#fde9aa";
const white: string = "#ffffff";
const grey: string = "#808080";
const black: string = "#000000";
const green: string = "#4d7728";
const blue: string = "#1a4f71";

export const theme = {
  screens: {
    smallMobile: 374,
    mobile: 480,
    tablet: 769,
    smallDesktop: 1024,
    specialScreen: 1120,
    desktop: 1200,
    maxDesktop: 1440,
  },
  colors: {
    beige: beige,
    white: white,
    grey: grey,
    black: black,
    green: green,
    blue: blue,
  },
  spacing: {
    zero: "4px",
    one: "8px",
    two: "16px",
    three: "24px",
    four: "32px",
    five: "40px",
    six: "48px",
    seven: "56px",
    eight: "64px",
    nine: "72px",
    ten: "80px",
    eleven: "88px",
    twelve: "96px",
    thirteen: "104px",
    fourteen: "112px",
    fifteen: "120px",
    sixteen: "128px",
  },
  fontSize: {
    extraSmall: "9px",
    semiSmall: "10px",
    small: "12px",
    medium: "14px",
    large: "16px",
    big: "18px",
    display5: "20px",
    display4: "22px",
    display3: "24px",
    display2: "26px",
    display1: "28px",
    display0: "30px",
    title5: "32px",
    title4: "34px",
    title3: "36px",
    title2: "38px",
    title1: "40px",
    title0: "50px",
  },
  fontWeight: {
    light: 300,
    regular: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
  },
  textAlign: {
    center: "center",
    left: "left",
    right: "right",
  },
  borderRadius: {
    none: "none",
    extraSmall: "4px",
    small: "8px",
    big: "16px",
    round: "24px",
    large: "32px",
    circle: "50%",
  },
};
